// Auto-generated by frontend-rtl-gen
// Design: rr_arbiter_3to1
// Module: rr_arbiter_3to1
// Generated: 2026-08-18
// Source: stage4_rtl_architecture.json + stage3_microarch_analysis.json

module rr_arbiter_3to1 #(
  parameter int DATA_WIDTH = 32
) (
  input  logic                         clk_i,
  input  logic                         rst_n_i,

  input  logic [2:0]                   in_valid_i,
  output logic [2:0]                   in_ready_o,
  input  logic [2:0][DATA_WIDTH-1:0]   in_data_i,

  output logic                         out_valid_o,
  input  logic                         out_ready_i,
  output logic [DATA_WIDTH-1:0]        out_data_o,
  output logic [2:0]                   grant_o
);

  localparam int NUM_INPUTS = 3;

  logic                         out_valid_q;
  logic [DATA_WIDTH-1:0]        out_data_q;
  logic [2:0]                   grant_q;
  logic [1:0]                   arb_ptr_q;

  logic [2:0]                   sel_oh;
  logic [DATA_WIDTH-1:0]        sel_data;
  logic                         sel_valid;
  logic                         can_accept;
  logic [1:0]                   scan_start;
  logic [1:0]                   grant_idx_q;

  function automatic logic [1:0] next_idx(input logic [1:0] idx);
    if (idx == 2'd2) begin
      next_idx = 2'd0;
    end else begin
      next_idx = idx + 2'd1;
    end
  endfunction

  function automatic logic [1:0] onehot_to_idx(input logic [2:0] onehot);
    unique case (onehot)
      3'b010:  onehot_to_idx = 2'd1;
      3'b100:  onehot_to_idx = 2'd2;
      default: onehot_to_idx = 2'd0;
    endcase
  endfunction

  assign out_valid_o = out_valid_q;
  assign out_data_o  = out_data_q;
  assign grant_o     = out_valid_q ? grant_q : 3'b000;

  assign can_accept = (!out_valid_q) || out_ready_i;
  assign grant_idx_q = onehot_to_idx(grant_q);
  assign scan_start = (out_valid_q && out_ready_i) ? next_idx(grant_idx_q) : arb_ptr_q;

  always_comb begin
    sel_oh    = 3'b000;
    sel_data  = '0;
    sel_valid = 1'b0;

    for (int unsigned offset = 0; offset < NUM_INPUTS; offset++) begin
      int unsigned idx;

      idx = scan_start + offset;
      if (idx >= NUM_INPUTS) begin
        idx = idx - NUM_INPUTS;
      end

      if (!sel_valid && in_valid_i[idx]) begin
        sel_oh[idx] = 1'b1;
        sel_data    = in_data_i[idx];
        sel_valid   = 1'b1;
      end
    end
  end

  assign in_ready_o = can_accept ? sel_oh : 3'b000;

  always_ff @(posedge clk_i or negedge rst_n_i) begin
    if (!rst_n_i) begin
      out_valid_q <= 1'b0;
      out_data_q  <= '0;
      grant_q     <= 3'b000;
      arb_ptr_q   <= 2'd0;
    end else begin
      if (out_valid_q && out_ready_i) begin
        arb_ptr_q <= next_idx(grant_idx_q);
      end

      if (can_accept) begin
        if (sel_valid) begin
          out_valid_q <= 1'b1;
          out_data_q  <= sel_data;
          grant_q     <= sel_oh;
        end else begin
          out_valid_q <= 1'b0;
          out_data_q  <= '0;
          grant_q     <= 3'b000;
        end
      end
    end
  end

endmodule
