// Auto-generated by frontend-tb-gen
// Design: rr_arbiter_3to1
// Updated: 2026-08-18
// Authority: stage1_spec_extraction.json (NOT RTL)

`timescale 1ns/1ps

module tb_rr_arbiter_3to1;

  localparam int DATA_WIDTH = 32;

  logic                         clk_i;
  logic                         rst_n_i;
  logic [2:0]                   in_valid_i;
  logic [2:0]                   in_ready_o;
  logic [2:0][DATA_WIDTH-1:0]   in_data_i;
  logic                         out_valid_o;
  logic                         out_ready_i;
  logic [DATA_WIDTH-1:0]        out_data_o;
  logic [2:0]                   grant_o;

  int unsigned total_outputs;
  int unsigned grant_count [3];
  int unsigned case_count;

  rr_arbiter_3to1 #(
    .DATA_WIDTH(DATA_WIDTH)
  ) dut (
    .clk_i       (clk_i),
    .rst_n_i     (rst_n_i),
    .in_valid_i  (in_valid_i),
    .in_ready_o  (in_ready_o),
    .in_data_i   (in_data_i),
    .out_valid_o (out_valid_o),
    .out_ready_i (out_ready_i),
    .out_data_o  (out_data_o),
    .grant_o     (grant_o)
  );

  initial begin
    clk_i = 1'b0;
    forever #5 clk_i = ~clk_i;
  end

  initial begin
    if ($test$plusargs("fsdb")) begin
      $fsdbDumpfile("dump.fsdb");
      $fsdbDumpvars(0, tb_rr_arbiter_3to1);
      $fsdbDumpMDA();
    end else if ($test$plusargs("vcd")) begin
      $dumpfile("dump.vcd");
      $dumpvars(0, tb_rr_arbiter_3to1);
    end
  end

  task automatic fail(input string msg);
    begin
      $display("TEST_FAIL: %s at time %0t", msg, $time);
      $fatal(1);
    end
  endtask

  task automatic begin_case(input string name);
    begin
      case_count++;
      $display("TEST_CASE_BEGIN[%0d]: %s at time %0t", case_count, name, $time);
    end
  endtask

  task automatic pass_case(input string name);
    begin
      $display("TEST_CASE_PASS[%0d]: %s at time %0t", case_count, name, $time);
    end
  endtask

  function automatic bit is_onehot0(input logic [2:0] value);
    is_onehot0 = (value == 3'b000) ||
                 (value == 3'b001) ||
                 (value == 3'b010) ||
                 (value == 3'b100);
  endfunction

  task automatic apply_reset;
    begin
      in_valid_i  = 3'b000;
      in_data_i   = '0;
      out_ready_i = 1'b1;
      rst_n_i     = 1'b0;
      repeat (3) @(posedge clk_i);
      rst_n_i = 1'b1;
      repeat (2) @(posedge clk_i);

      if (out_valid_o !== 1'b0) fail("out_valid_o must reset to 0");
      if (out_data_o !== '0)    fail("out_data_o must reset to 0");
      if (grant_o !== 3'b000)   fail("grant_o must reset to 0");
    end
  endtask

  task automatic clear_inputs;
    begin
      @(negedge clk_i);
      in_valid_i = 3'b000;
      in_data_i  = '0;
    end
  endtask

  task automatic wait_output_and_check(
    input logic [DATA_WIDTH-1:0] exp_data,
    input logic [2:0]            exp_grant,
    input string                 tag
  );
    begin
      #1;
      while (!(out_valid_o && out_ready_i)) begin
        @(negedge clk_i);
        #1;
      end

      if (out_data_o !== exp_data) begin
        $display("Expected %s data 0x%08x, got 0x%08x", tag, exp_data, out_data_o);
        fail("output data mismatch");
      end

      if (grant_o !== exp_grant) begin
        $display("Expected %s grant %03b, got %03b", tag, exp_grant, grant_o);
        fail("grant mismatch");
      end

      total_outputs++;
      if (exp_grant[0]) grant_count[0]++;
      if (exp_grant[1]) grant_count[1]++;
      if (exp_grant[2]) grant_count[2]++;

      @(posedge clk_i);
    end
  endtask

  task automatic test_reset_initial_priority;
    begin
      begin_case("reset_initial_priority_input0");
      apply_reset();

      @(negedge clk_i);
      in_valid_i  = 3'b111;
      in_data_i[0] = 32'h0000_0100;
      in_data_i[1] = 32'h0000_0200;
      in_data_i[2] = 32'h0000_0300;

      #1;
      if (in_ready_o !== 3'b001) begin
        fail("after reset, first ready must select input0 when all inputs are valid");
      end

      wait_output_and_check(32'h0000_0100, 3'b001, "initial priority");
      clear_inputs();
      pass_case("reset_initial_priority_input0");
    end
  endtask

  task automatic test_skip_invalid_inputs;
    begin
      begin_case("skip_invalid_inputs_from_pointer");
      apply_reset();

      @(negedge clk_i);
      in_valid_i  = 3'b100;
      in_data_i[0] = 32'h0000_1000;
      in_data_i[1] = 32'h0000_2000;
      in_data_i[2] = 32'h0000_3000;

      #1;
      if (in_ready_o !== 3'b100) begin
        fail("arbiter must skip invalid input0/input1 and select valid input2");
      end

      wait_output_and_check(32'h0000_3000, 3'b100, "skip invalid");
      clear_inputs();
      pass_case("skip_invalid_inputs_from_pointer");
    end
  endtask

  task automatic test_full_load_rotation;
    begin
      begin_case("full_load_rotation_0_1_2");
      apply_reset();
      total_outputs = 0;
      grant_count[0] = 0;
      grant_count[1] = 0;
      grant_count[2] = 0;

      @(negedge clk_i);
      in_valid_i  = 3'b111;
      in_data_i[0] = 32'h0000_0010;
      in_data_i[1] = 32'h0000_0020;
      in_data_i[2] = 32'h0000_0030;

      wait_output_and_check(32'h0000_0010, 3'b001, "rotation beat 0");
      wait_output_and_check(32'h0000_0020, 3'b010, "rotation beat 1");
      wait_output_and_check(32'h0000_0030, 3'b100, "rotation beat 2");
      wait_output_and_check(32'h0000_0010, 3'b001, "rotation beat 3");
      wait_output_and_check(32'h0000_0020, 3'b010, "rotation beat 4");
      wait_output_and_check(32'h0000_0030, 3'b100, "rotation beat 5");

      if (grant_count[0] != 2 || grant_count[1] != 2 || grant_count[2] != 2) begin
        fail("grant counts must be balanced under full load");
      end

      clear_inputs();
      pass_case("full_load_rotation_0_1_2");
    end
  endtask

  task automatic test_backpressure_freezes_output;
    logic [DATA_WIDTH-1:0] held_data;
    logic [2:0]            held_grant;
    begin
      begin_case("backpressure_freezes_output_and_ready");
      apply_reset();

      @(negedge clk_i);
      in_valid_i[0] = 1'b1;
      in_data_i[0]  = 32'h0000_00a5;

      @(posedge clk_i);
      #1;
      if (in_ready_o[0] !== 1'b1) fail("input0 must be accepted when output register is empty");
      in_valid_i[0] = 1'b0;

      @(negedge clk_i);
      if (out_valid_o !== 1'b1) fail("accepted input must appear at output");
      out_ready_i = 1'b0;
      held_data   = out_data_o;
      held_grant  = grant_o;

      repeat (3) begin
        @(negedge clk_i);
        if (out_valid_o !== 1'b1) fail("out_valid_o must stay high under backpressure");
        if (out_data_o !== held_data) fail("out_data_o must stay stable under backpressure");
        if (grant_o !== held_grant) fail("grant_o must stay stable under backpressure");
        if (in_ready_o !== 3'b000) fail("all inputs must be backpressured while output is stalled");
      end

      out_ready_i = 1'b1;
      @(posedge clk_i);
      #1;
      if (out_valid_o !== 1'b0) fail("output register must empty after stalled beat is consumed");
      pass_case("backpressure_freezes_output_and_ready");
    end
  endtask

  task automatic test_ready_onehot_and_refill;
    begin
      begin_case("ready_onehot_and_consume_refill");
      apply_reset();

      @(negedge clk_i);
      in_valid_i  = 3'b011;
      in_data_i[0] = 32'h0000_0a00;
      in_data_i[1] = 32'h0000_0b00;
      in_data_i[2] = 32'h0000_0c00;

      #1;
      if (!is_onehot0(in_ready_o)) fail("in_ready_o must be one-hot or zero");
      if (in_ready_o !== 3'b001) fail("first selected input must be input0");

      wait_output_and_check(32'h0000_0a00, 3'b001, "onehot first beat");

      @(negedge clk_i);
      if (!is_onehot0(in_ready_o)) fail("in_ready_o must remain one-hot during refill");
      if (in_ready_o !== 3'b001) begin
        fail("after input1 refill, next ready candidate must wrap past invalid input2 to input0");
      end

      wait_output_and_check(32'h0000_0b00, 3'b010, "onehot refill beat");
      clear_inputs();
      pass_case("ready_onehot_and_consume_refill");
    end
  endtask

  initial begin
    bit selected;

    selected = 1'b0;
    case_count = 0;
    total_outputs = 0;
    grant_count[0] = 0;
    grant_count[1] = 0;
    grant_count[2] = 0;

    if ($test$plusargs("case_reset")) begin
      selected = 1'b1;
      test_reset_initial_priority();
    end

    if ($test$plusargs("case_skip")) begin
      selected = 1'b1;
      test_skip_invalid_inputs();
    end

    if ($test$plusargs("case_rotation")) begin
      selected = 1'b1;
      test_full_load_rotation();
    end

    if ($test$plusargs("case_backpressure")) begin
      selected = 1'b1;
      test_backpressure_freezes_output();
    end

    if ($test$plusargs("case_onehot")) begin
      selected = 1'b1;
      test_ready_onehot_and_refill();
    end

    if (!selected) begin
      test_reset_initial_priority();
      test_skip_invalid_inputs();
      test_full_load_rotation();
      test_backpressure_freezes_output();
      test_ready_onehot_and_refill();
    end

    repeat (5) @(posedge clk_i);
    $display("TEST_PASS: rr_arbiter_3to1 focused round-robin self-checks passed");
    $finish;
  end

endmodule
